### ISSUE TITLE
For newsroom, create new news item about the official signing

### ISSUE THREAD

**Issue by samtaggart** [ourworldfreezone/www_ourworld_freezone#6]
Take an image from what was shared in internal group. We can keep the details minimal – just say that we are honored to have signed the contract with the government of Zanzibar to officialize the OurWorld Free Zone. Let me know if you need any help.

**Comment by sasha-astiadi** [comment]
<img width="1440" alt="Screenshot 2023-08-15 at 00 27 39" src="https://github.com/ourworldfreezone/www_ourworld_freezone/assets/43240801/d57e00cf-6863-4f8c-aa26-187893b4bd32">
